import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../globals.css';
import Providers from '../components/Providers';
import Header from '../api/auth/[...nextauth]/Header';
import { Copyright } from 'lucide-react';
import Link from 'next/link';

const geistSans = localFont({
  src: '../fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: '../fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="bg-gradient-to-r from-white to-mint-cream/60">
      <Providers>
        <Header />
        <div className="min-h-screen">
          <div className="min-h-full w-full max-w-7xl mx-auto font-[family-name:var(--font-geist-sans)]">
            {children}
          </div>
        </div>
      </Providers>
      <footer className="px-8 py-4">
        <div className="flex items-center gap-2">
          ResuGenie created by{' '}
          <Link href="https://maikpleines.com" className="underline">
            Maik Pleines
          </Link>
          <Copyright size={16} />
          {new Date().getFullYear()}
        </div>
      </footer>
    </div>
  );
}
