import type { Metadata } from 'next';
import '../globals.css';
import Providers from '../components/Providers';
import { Copyright, Dot } from 'lucide-react';
import Link from 'next/link';
import { redirect } from 'next/navigation';
import { auth } from '@/auth';
import { Badge } from '@/components/ui/badge';
import Footer from '../components/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (session?.user != null) {
    redirect('/dashboard');
  }

  return (
    <div>
      <Providers>
        <div className="min-h-screen">
          <div className="min-h-full w-full font-[family-name:var(--font-geist-sans)]">
            {children}
          </div>
        </div>
      </Providers>
      <Footer />
    </div>
  );
}
